<?php $getTask = ($this->editTask);?>
<h2 class="text-center text-3xl my-8">Edit task nº <?php echo $getTask["id"]?></h2>
<div class="mx-auto px-10 w-96 border border-black pb-8">
  <form method="post">
    <div class="w-full text-center">
      <p class="py-4">
        Name of your task
      </p>
      <input type="text" name="task" value="<?php echo $getTask["task"]?>"
        class="text-sm border-2 text-slate-500 border-gray-900 p-2.5 w-48" />
    </div>
    <div class="w-full text-center">
      <p class="py-4">
        User Name
      </p>
      <input type="text" name="user" value="<?php echo $getTask["user"]?>"
        class="text-sm border-2 text-slate-500 border-gray-900 p-2.5 w-48" />
    </div>
    <div class="w-full text-center">
      <p class="py-4">
        State
      </p>
      <select name="state" value="<?php echo $getTask["state"]?>"
        class="text-sm border-2 text-slate-500 border-gray-900 p-2.5 w-48">
        <option value="pending">pending</option>
        <option value="doing">doing</option>
        <option value="finish">finish</option>
      </select>
    </div>
    <div class="w-full text-center">
      <p class="py-4">
        Start date
      </p>
      <input type="datetime-local" name="sdate" value="<?php echo $getTask["sdate"]?>"
        class="text-sm border-2 text-slate-500 border-gray-900 p-2.5 w-48">
    </div>
    <div class="w-full text-center">
      <p class="py-4">
        Finish date
      </p>
      <input type="datetime-local" name="fdate" value="<?php echo $getTask["fdate"]?>"
        class="text-sm border-2 text-slate-500 border-gray-900 p-2.5 w-48">
    </div>
    <div class="w-full text-center pt-8">
      <input type="submit" value="UPDATE" class="bg-black custom-btn btn-3 text-center mr-2 hover:bg-black">
    </div>
  </form>
</div>
