<footer class="fixed bottom-0 left-0 right-0 bg-white text-center">
    <h1 class="flex justify-center">Todo Task <?php echo date("Y"); ?> © made with <svg
            xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mt-1" fill=" none" viewBox="0 0 24 24"
            stroke="currentColor" stroke-width="1">
            <path stroke-linecap="round" stroke-linejoin="round"
                d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
        </svg><span> by </span><a href="https://quexulo.cat" target="_blank" class="underline ml-1"> quexulo.cat</a>
    </h1>
</footer>