<header class="flex justify-center bg-white border p-3 mb-2">
    <div class="flex justify-center ">
        <a href="../web/" class="custom-btn btn-3 text-center mr-2"><span>HOME</span></a>
        <a href="../web/add" class="custom-btn btn-3 text-center mr-2"><span>NEW TASK</span></a>
        <a href="#open-modal" class="custom-btn btn-3 text-center mr-2"><span>INFORMATION</span></a>
        
    </div>
</header>

<div id="open-modal" class="modal-window">
    <div class="modalespai">
        <a href="#" title="Close" class="modal-close">
            Close
        </a>
        <p class="text-center titol mb-2">Instructions</p>
        <p class="mb-3">Hi User, you can create, update, delete and show tasks.</p>
        <p class="mb-3">Enjoy !!!</p>
     
    </div>
</div>